version: 2.1

orbs:
    bridgecrew: bridgecrew/bridgecrew@1.0.2

jobs:
    build:
      executor: bridgecrew/default
      steps:
        - checkout
        - bridgecrew/scan:
            directory: '.'
            output: "junitxml"
            api-key-variable: "b4667191-6e30-5489-bbb8-030c3f7772eb"