version: 2.1

orbs:
    bridgecrew: bridgecrew/bridgecrew@1.0.2

jobs:
    build:
      executor: bridgecrew/default
      steps:
        - checkout
        - bridgecrew/scan:
            directory: '.'
            api-key-variable: BC_API_KEY
